### PR TITLE
PSP-8414 : Select one or multiple properties for H120 Generation

### PR DESCRIPTION
**Pull request by eddherrera**
image

image

### CODE REVIEW

**Comment by eddherrera** [comment]
*** Requires template update before merge

**Comment by devinleighsmith** [comment]
Trying to remove a property that is on a compensation throws an unhandled db exception. Probably want to add to this logic: 

`
if (acqFileProperties.PimsTakes.Any() || acqFileProperties.PimsInthldrPropInterests.Any())
{
    throw new BusinessRuleViolationException("You must remove all takes and interest holders from an acquisition file property before removing that property from an acquisition file");
}
`

**Comment by devinleighsmith** [comment]
The implemented view display of selected properties doesn't match figma and will probably be brought up as a bug by the FT team. Is this something you discussed with Ana, and is that documented on the story somewhere?
implementation:
image
mockup:
image

**Comment by devinleighsmith** [comment]
Also this AC is not met:
image

**Comment by devinleighsmith** [comment]
@eddherrera if I select/deselect multiple properties at a time the current implementation only seems to log one of my selections/deselections when I save.

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
some mismatched requirements, functional issues.

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
