### PR TITLE
PSP PIMS v16.01

### PR DESCRIPTION
**Pull request by dfilteau**
PSP_PIMS S16.01 Sprint 16 2021-Dec-03
- Added tables:
  - PIMS_TENANT
- Added seed data tables:
  - 51_DML_PIMS_ROLE.sql
  - 73_DML_PIMS_LEASE_STATUS_TYPE.sql
  - 74_DML_PIMS_CLAIM.sql
  - 75_DML_PIMS_ROLE_CLAIM.sql
  - 76_DML_PIMS_ORGANIZATION.sql
  - 77_DML_PIMS_TENANT.sql
- Requires additional metadata to meet standards

### CODE REVIEW

**Comment by dfilteau** [comment]
Added v16.02: Alter the PIMS_CONTACT_MGR_VW view to reference ADDRESS_USAGE_TYPE_CODE = 'MAILING' rather that 'MAILADDR'

**Comment by devinleighsmith** [comment]
Hey @dfilteau , I'm unable to run the alter up going from PSP_PIMS_S16_00 to PSP_PIMS_S16_01. This seems to be the culprit:
`-- Drop procedure dbo.pims_error_handling
PRINT N'Drop procedure dbo.pims_error_handling'
GO
DROP PROCEDURE [dbo].[pims_error_handling]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

-- Drop procedure dbo.pims_error_handling
PRINT N'Drop procedure dbo.pims_error_handling'
GO
DROP PROCEDURE [dbo].[pims_error_handling]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO`

Not sure why a script generated by aqua data studio would try and delete the same stored procedure twice, but there you go.

**Comment by dfilteau** [comment]
Updated Alter Up to remove duplicate drop of pims_error_handling procedure

**Comment by dfilteau** [comment]
Further update to 01_PSP_PIMS_S16_00_Alter_Up.sql

**Comment by dfilteau** [comment]
Commented out the dropping of TENNTX_PK

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
