### PR TITLE
update sonarqube configuration for newer version.

### PR DESCRIPTION
**Pull request by devinleighsmith**

### CODE REVIEW

**Comment by devinleighsmith** [comment]
this corresponds to version 8.9.6.50800 (which is considered safe in regards to log4j).

**Review by asanchezr — APPROVED** [review]

**Comment by asanchezr** [comment]
Approved but I thought there were newer images available - 9.2 maybe?

**Comment by devinleighsmith** [comment]
@asanchezr 9.x aren't available as free community versions. We are using the newest lts-community release.

**Comment by asanchezr** [comment]
I see - bummer

**Pull request merged**
