### PR TITLE
Feature/psp 4243

### PR DESCRIPTION
**Pull request by Maheshbabu28**

### CODE REVIEW

**Comment by devinleighsmith** [comment]
When clicking on an previously selected row, the row does not deselect (as called out on the bug ticket). I don't think that is a big deal, but please confirm with Dev if that functionality is required or not.

**Comment by devinleighsmith** [comment]
Also, yesterday when we talked about this story I asked for tests to be added to cover this functionality, please add that since this functionality has been unstable in the past.

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
requested test coverage

**Comment by Maheshbabu28** [comment]
@devinleighsmith Ideally for radio button will not deselect once it is selected atleast one button.
As of now we don't have any test cases for complete table component itself.

**Comment by devinleighsmith** [comment]
@Maheshbabu28 what is the status of this?

**Comment by Maheshbabu28** [comment]
@devinleighsmith I reached out Dev yesterday and he said it is ok not to deselect the selected row.

**Review by devinleighsmith — APPROVED** [review]

**Comment by devinleighsmith** [comment]
@Maheshbabu28  This is approved but do not merge until after the demo.

**Comment by Maheshbabu28** [comment]
@devinleighsmith Sure Devin

**Pull request merged**
