### PR TITLE
PSP-7499: UI/UX Clean Up - Contact List

### PR DESCRIPTION
**Pull request by stairaku**
image

### CODE REVIEW

**Comment by devinleighsmith** [comment]
This icon hasn't been updated as per the mockup.

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
see comments

**Comment by stairaku** [comment]
@devinleighsmith could you tell me exactly which icon and which spacing you're refencing to? I just see the comments on the conversation tab but I don't see the reference on the code. Thanks!

**Comment by devinleighsmith** [comment]
image

**Comment by devinleighsmith** [comment]
image

**Comment by stairaku** [comment]
Updated Contact List:
image

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
