### PR TITLE
PSP-9331: UI UX Clean Up - Replace notes field

### PR DESCRIPTION
**Pull request by stairaku**
image
image
image
image
image

### CODE REVIEW

**Comment by asanchezr** [comment]
@stairaku - I updated the labels on this PR as this is a 5.6 feature

**Comment by devinleighsmith** [comment]
@sue, there may be a missed note field on the disposition offer details form.

**Comment by devinleighsmith** [comment]
Please ensure that any yup schemas referring to these updated fields have their error messages corrected to refer to the new field name (ie. max length for notes fields).

**Comment by devinleighsmith** [comment]
May also be missing disposition offer notes field

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
see comments, may be a few missing updates in yup schemas, disposition.

**Comment by stairaku** [comment]
> @sue, there may be a missed note field on the disposition offer details form.

Let me check, I'll update this PR shortly

**Comment by stairaku** [comment]
@devinleighsmith I updated the PR and add the Disposition comments changes and the Property Details Yup message. I also went ahead and updated all Property details labels that didn't follow the pattern we are now managing (Upper case only at the start of the label).

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
