### PR TITLE
Psp 2114

### PR DESCRIPTION
**Pull request by devinleighsmith**
Add lease page

### CODE REVIEW

**Comment by devinleighsmith** [comment]
Need to update/add tests still

**Comment by FuriousLlama** [comment]
@devinleighsmith Could you add a screenshot of the changes?

**Comment by devinleighsmith** [comment]
> @devinleighsmith Could you add a screenshot of the changes?

yes, sorry one minute

**Comment by devinleighsmith** [comment]
fully zoomed out to fit in a single screenshot

image

**Comment by devinleighsmith** [comment]
Think I have a gif tool around somewhere, need to dust that off.

**Review by FuriousLlama — APPROVED** [review]

**Pull request merged**
