### PR TITLE
IS-26 Database Schema Changes

### PR DESCRIPTION
**Pull request by dfilteau**
PSP_PIMS S26.00 Sprint 26 2022-Apr-13
- Added tables
  - PIMS_PROP_RESEARCH_PURPOSE_TYPE
  - PIMS_PRF_PROP_RESEARCH_PURPOSE_TYPE
  - PIMS_PPH_STATUS_TYPE
- Altered tables:
  - PIMS_PROPERTY
  - PIMS_PROPERTY_HIST
  - PIMS_PROPERTY_RESEARCH_FILE
  - PIMS_PROPERTY_RESEARCH_FILE_HIST
- Seed data table changes:
  - PIMS_PROPERTY_CLASSIFICATION_TYPE
    - Added 'UNKNOWN'
  - PIMS_DATA_SOURCE_TYPE
    - Added 'PMBC'
- Requires additional metadata to meet standards

### CODE REVIEW

**Comment by FuriousLlama** [comment]
@dfilteau Looks like the constraints are set to NOT ENFORCED. Is that an expected change for the foreign keys?

**Review by FuriousLlama — CHANGES_REQUESTED** [review]
Foreign key constrains not enforced

**Comment by dfilteau** [comment]
NOT ENFORCED statements removed in 02_PSP_PIMS_S26_00_Build.sql

**Comment by FuriousLlama** [comment]
@dfilteau Found an issue with the encoding of text on the BcaOwnershipGroup. Looks like some characters are not coming through correctly (e.g. "Floor, as required for mail to be sent to the ownerï¿½s mailing address.").

This does not happen when doing a build.

**Comment by FuriousLlama** [comment]
Not directly related to this PR, but the Alter Up operation on s25_01 is not doing the same as the Build. The PropertBoundaryView and PropertyLocationView address are non-nullable. This should be fixed in TEST before it goes into the next domain

**Review by FuriousLlama — APPROVED** [review]

**Review by FuriousLlama — CHANGES_REQUESTED** [review]
Waiting for fixes to s25_01 to be in sync

**Review by FuriousLlama — APPROVED** [review]

**Pull request merged**
