### PR TITLE
Feature/psp 5023

### PR DESCRIPTION
**Pull request by Maheshbabu28**

### CODE REVIEW

**Comment by asanchezr** [comment]
@Maheshbabu28 please fix file conflicts

**Comment by Maheshbabu28** [comment]
@asanchezr Resolved the conflicts

**Comment by devinleighsmith** [comment]
The default map view is not displaying properly:
image

**Comment by devinleighsmith** [comment]
It looks like selecting a tab is changing the active url, but refreshing the page will not navigate to that tab. I don't think this is a big deal since it is not a requirement, but please either remove the modifications to the url or make the url edits actually affect the active tab.

**Comment by devinleighsmith** [comment]
Please correct the comments that were made in sprint review today:

Too much spacing between labels and values on details tab.
effective date and moti contact labels are compressed vertically on details tab administration section.
too much spacing between labels and values on insurance tab.
too much spacing between labels and values on improvements tab.

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
see comments.

**Comment by Maheshbabu28** [comment]
@devinleighsmith  Did changes in the url as there was a requirement to show payments and deposit in full width and there is no way to know on which tab we are after tab click. Using hash tab names in url to show these tabs in full widht.
Let me know if you think there is any other better way to do it.

**Comment by devinleighsmith** [comment]
@Maheshbabu28 please correct the test failures and then I'll re-review this PR.

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
