### PR TITLE
Pims api to Frontend ts generator and generated files

### PR DESCRIPTION
**Pull request by FuriousLlama**

### CODE REVIEW

**Comment by devinleighsmith** [comment]
I'm not going to review all 460 files, are there any files that I should take a look at or are we confident based on your presentation from Friday that this is good to ship as-is?

**Comment by FuriousLlama** [comment]
> I'm not going to review all 460 files, are there any files that I should take a look at or are we confident based on your presentation from Friday that this is good to ship as-is?
> 
> @FuriousLlama

I am pretty confident things will work. If you have spare cycles having a second set of eyes on the changes to the controllers would be good given those where more prone to error.

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
@FuriousLlama I checked this out and this appears to break the keycloak-sync. Can you open that solution and fix any errors please?

**Comment by devinleighsmith** [comment]
@FuriousLlama keycloak-sync isn't compiling still. Does this PR depend on something else maybe?

**Comment by FuriousLlama** [comment]
> @FuriousLlama keycloak-sync isn't compiling still. Does this PR depend on something else maybe?

should be compiling now!

**Comment by FuriousLlama** [comment]
@devinleighsmith Ready for re-review.

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
