### PR TITLE
PSP-3685: Reusable Component - Close Activity (General)

### PR DESCRIPTION
**Pull request by Maheshbabu28**

### CODE REVIEW

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
Putting this one on hold for now, I have some outstanding questions for Bobbi about the lo-fi design that Julian put together for this story.

**Comment by Maheshbabu28** [comment]
image

image

**Comment by devinleighsmith** [comment]
@Maheshbabu28 I checked this out but this doesn't seem right still, I am able to modify the description while in the complete status. The story states that:

Other than a new status change or add/edit/delete NOTES and DOCUMENTS, additional changes CANNOT be made to the Activity when in a COMPLETED status.

and 

Other than a new status change or add/edit/delete NOTES and DOCUMENTS, additional changes CANNOT be made to the Activity when in a CANCELLED  status.

So the user should not be able to make changes to the activity form when it is in those two statuses.

**Comment by Maheshbabu28** [comment]
@devinleighsmith Made updates as per your comments.

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
