### PR TITLE
PSP-7498: UI/UX Clean Up - Contacts - View

### PR DESCRIPTION
**Pull request by stairaku**

### CODE REVIEW

**Comment by devinleighsmith** [comment]
Some minor areas where the mockup doesn't seem to match the implementation, have these been approved by Ana? if so, they need to be updated in the mockup or this will fail FT:

image

**Comment by devinleighsmith** [comment]
Also some issues here: corporation vs incorporation. missing tooltip:

image

**Comment by devinleighsmith** [comment]
Please check with ana on whether the incorporation number should be required as labelled on the mockup:

image

**Comment by devinleighsmith** [comment]
See this: organization section doesn't exist in edit mockup:

image

**Review by devinleighsmith — CHANGES_REQUESTED** [review]
Please work with Ana to close gap in differences between mockups and implementation.

**Comment by stairaku** [comment]
I have updated the forms for View and Update for both Personal and Organization contacts accordingly to comments and discussed with Ana which changes she needs to be done on her end. She confirmed she needs to update these mockups since last time they were updated were on November 2023. 

The new status look and feel are not currently on the mockup but the details are attached on the JIRA ticket as a comment.

Attaching current forms for approval:
image
image
image
image

**Review by devinleighsmith — APPROVED** [review]

**Pull request merged**
