### PR TITLE
Discuss exceptions to security scans

### PR DESCRIPTION
**Pull request by asanchezr**
Use this PR to discuss what to do with the potential secrets remaining in the source code.

### CODE REVIEW

**Comment by devinleighsmith** [comment]
Had a look at the report, looks like all errors with realm.json which is just for local dev, so I don't see any issues leaving that in.

**Comment by asanchezr** [comment]
This is the output from the security scan at this point.

:warning: The security scan detected 6 potential secrets in the code.

```
path                                      line  secret
--------------------------------------  ------  ------------------
auth/keycloak/config/realm-export.json     592  puLMCskW5P+eGUC...
auth/keycloak/config/realm-export.json     624  Oc+/f7zWC8tvpid...
auth/keycloak/config/realm-export.json     703  02MdIh5KlDbjtWM...
auth/keycloak/config/realm-export.json    2307  5mhHXrmgvJf6mz0...
auth/keycloak/config/realm-export.json    2320  MIIEpAIBAAKCAQE...
auth/keycloak/config/realm-export.json    2323  MIIClzCCAX8CBgF...
```

**Comment by asanchezr** [comment]
@sookeke - have you reviewed this PR yet?

**Review by sookeke — COMMENTED** [review]
Yes, it does seems like the auth/keycloak/config/realm-export.json is for local deployment and has no security implications for the project.

There's an email address that might be deemed personal information admin@pims.gov.bc.ca. Please remove this email address

Other than that, exempt this folder

**Comment by sookeke** [comment]
@asanchezr  I just confirmed admin@pims.gov.bc.ca is not a valid email on our host.

**Comment by asanchezr** [comment]
ok will remove

**Comment by asanchezr** [comment]
@sookeke - changes made as per your request:

- Added exception for **realm-export.json** to the automated secret scanning tool
- Removed personal information from **realm-export.json** 

Please feel free to approve the PR so we can merge this changes.

**Review by sookeke — APPROVED** [review]

**Review by Fosol — APPROVED** [review]

**Pull request merged**
